version: '3.8'

services:
  db-accounts:
    image: postgres:15
    container_name: banking-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: BancarDB
    volumes:
      - postgres-accounts:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  db-transactions:
    image: postgres:15
    container_name: transaction-db
    environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: TransactionsDB
    volumes:
        - postgres-transactions:/var/lib/postgresql/data
    ports:
        - "5433:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 
 
  accounts-app:
    build: ./Accounts
    container_name: accounts-app
    ports:
      - "8081:8081"
    depends_on:
      - db-accounts
      - kafka

  transactions-app:
    build: ./Transactions
    container_name: transactions-app
    ports:
      - "8082:8082"
    depends_on:
      - db-transactions
      - kafka

  logs-app:
    build: ./logs
    container_name: logs-app
    ports:
      - "8083:8083"
    depends_on:
      - kafka

volumes:
  postgres-accounts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/laurentiu/docker-volumes/postgres-accounts
  postgres-transactions:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/laurentiu/docker-volumes/postgres-transactions