server.port = 8081
spring.application.name=Accounts
#Keye de protectie pt JwtUtil
jwt.secret=cheiecsecretacfoarteclungacdeccelcputinc256cbiti
#Config baza de date
spring.main.allow-circular-references=true
spring.datasource.url=jdbc:postgresql://banking-db:5432/BancarDB
#spring.datasource.url=jdbc:postgresql://localhost:5432/BancarDB
spring.datasource.username = myuser
spring.datasource.password= mypassword

#Config hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Kafka Template

spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer



